name: MinGW Windows ARM64 CI Debugging


on:
  workflow_dispatch:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main ]

jobs:
  build-arm64:
    # Use GitHub's native Windows ARM64 runner
    runs-on: windows-11-arm

    defaults:
      run:
        # Force all workflow steps to run inside the MSYS2 bash environment
        shell: msys2 {0}

    steps:
#      - name: Checkout Source Code
#        uses: actions/checkout@v7
            
      - name: checkout recovery directory
        shell: powershell
        env:
          SECRET_URL: ${{ secrets.CI_DEBUG_ARTIFACT_URL }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          curl --request GET `
            --url "$env:SECRET_URL" `
            --header "Authorization: Bearer $env:GITHUB_TOKEN" `
            --header "Accept: application/vnd.github+json" `
            --header "X-GitHub-Api-Version: 2022-11-28"  `
            -o builddir.zip -L 
            


      - name: Unzip with PowerShell
        shell: powershell
        run: Expand-Archive -Path "builddir.zip" -DestinationPath "." -Force

      - name: list expanded dir
        run: |
          find . 

      - name: Setup MSYS2 and ARM64 Toolchain
        uses: msys2/setup-msys2@v2
        with:
          # Select the native Windows ARM64 environment
          msystem: CLANGARM64
          update: true
          # Install the necessary build tools and compilers
          install: >-
            mingw-w64-clang-aarch64-clang
            mingw-w64-clang-aarch64-toolchain
            git
            make
            cmake
            ninja
            mingw-w64-clang-aarch64-jansson
            mingw-w64-clang-aarch64-wxwidgets3.2-msw
            mingw-w64-clang-aarch64-lua
            mingw-w64-clang-aarch64-capstone
            mingw-w64-clang-aarch64-jbigkit
            mingw-w64-clang-aarch64-libbotan
            mingw-w64-clang-aarch64-libunistring
            mingw-w64-clang-aarch64-git
            mingw-w64-clang-aarch64-libarchive
            libarchive-devel
            mingw-w64-clang-aarch64-curl
            libcurl-devel
            libgpgme-devel
            openssl-devel
            mingw-w64-clang-aarch64-SDL2
            mingw-w64-clang-aarch64-SDL2_image
            mingw-w64-clang-aarch64-asciidoc
            mingw-w64-clang-aarch64-cairo
            mingw-w64-clang-aarch64-capstone
            mingw-w64-clang-aarch64-curl-winssl
            mingw-w64-clang-aarch64-cyrus-sasl
            mingw-w64-clang-aarch64-gnutls
            mingw-w64-clang-aarch64-gtk3
            mingw-w64-clang-aarch64-icu
            mingw-w64-clang-aarch64-jack2
            mingw-w64-clang-aarch64-leptonica
            mingw-w64-clang-aarch64-libarchive
            mingw-w64-clang-aarch64-libb2
            mingw-w64-clang-aarch64-libnfs
            mingw-w64-clang-aarch64-libslirp
            mingw-w64-clang-aarch64-libssh
            mingw-w64-clang-aarch64-lz4
            mingw-w64-clang-aarch64-pango
            mingw-w64-clang-aarch64-pdcurses
            mingw-w64-clang-aarch64-snappy
            mingw-w64-clang-aarch64-spice
            mingw-w64-clang-aarch64-usbredir
            mingw-w64-clang-aarch64-virglrenderer

            binutils
            mingw-w64-clang-aarch64-diffutils

            mingw-w64-clang-x86_64-nsis
            mingw-w64-clang-aarch64-ninja

      - name: Verify Compiler
        run: |
          clang --version
          gcc --version || true  # (Note: CLANGARM64 uses clang as the main driver)

      - name: TODO
        run: |
          echo "docs build is still disabled"

      

      - name: Build Project
        run: |
          export CC=clang
          export CXX=clang++
          # ./configure --disable-guest-agent-msi --disable-werror
          # make
          
      - name: try build installer
        run: |
          date=$(date +%Y%m%d)
          mkdir dist
          INSTALLER=dist/qemu-$ARCH-setup-$date.exe
          make installer SIGNCODE=true
      # Recursive list using PowerShell (default shell on Windows runners)
      - name: List all files recursively (Bash)
        if: always()
        run: find .

      #debugging ci workflow
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: builddir-clangarm64-msys2-${{ github.run_number }}       # The name of your downloadable zip file
          path: ./                  # The directory or file path to upload
          retention-days: 7            # Optional: How long to keep the files (Default: 90)
          if-no-files-found: error     # Optional: Fails the build if 'dist' is missing
